export const initialReviewData = [
  {
    id: 1,
    productName: "Hydrating Facial Toner REV-341125",
    reviewId: "REV-34125",
    text: "Produk toner ini sangat menyegarkan dan melembabkan kulit saya. Pengiriman cepat dan kemasan rapi! recommended",
    isBlackScreen: true,
    imageUrl: null,
    confidenceScore: 95,
    statusColor: "danger", // 'danger', 'success', 'warning'
    statusText: "High Risk",
    logicExplanation: "Deteksi Konflik Multimodal:\n\n1. Analisis Teks (Positif): Pengguna memuji produk ('menyegarkan', 'melembabkan', 'recommended').\n2. Analisis Gambar (Anomali): Gambar yang diunggah hanya berupa layar hitam pekat, tidak ada objek atau produk yang terdeteksi.\n\nKesimpulan: Terdapat ketidaksesuaian tinggi (95% Risk) antara sentimen teks dengan bukti visual. Indikasi kuat ulasan palsu untuk mengejar poin/insentif platform.",
    mobileExplanation: "Mohon jangan khawatir Ibu Ratna, ulasan ini kami curigai palsu karena pembeli memuji produk dengan sangat baik, tapi anehnya hanya mengunggah foto layar hitam gelap. Silakan hapus ulasan ini jika dirasa merugikan rating toko Ibu.",
    isDeleted: false,
    isOverridden: false,
  },
  {
    id: 2,
    productName: "Ceramic Mugs Set",
    reviewId: "REV-88711",
    text: "Gelasnya cantik sekali, pas buat ngopi sore. Packing aman.",
    isBlackScreen: false,
    imageUrl: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&q=80&w=300&h=200",
    confidenceScore: 98,
    statusColor: "success",
    statusText: "Safe",
    logicExplanation: "Analisis Multimodal:\n\n1. Analisis Teks (Positif): Pengguna memuji ('cantik sekali', 'packing aman').\n2. Analisis Gambar (Valid): Terdeteksi objek cangkir/gelas (Mug) yang sesuai dengan kategori produk. Kondisi visual baik, tidak ada cacat.\n\nKesimpulan: Konsistensi tinggi (98% Safe) antara sentimen teks dan bukti visual. Ulasan organik dan valid.",
    mobileExplanation: "Semuanya aman Ibu Ratna. Ulasan ini memuji produk dengan tulus dan fotonya terlihat jelas (sesuai barangnya). Tidak ada indikasi penipuan.",
    isDeleted: false,
    isOverridden: false,
  },
  {
    id: 3,
    productName: "Vas Bunga Kaca Estetik",
    reviewId: "REV-12903",
    text: "Wah, barangnya bagus banget sampai hancur berkeping-keping pas sampai. Mantap kurirnya!",
    isBlackScreen: false,
    imageUrl: "https://images.unsplash.com/photo-1615800002234-2e635767b45a?auto=format&fit=crop&q=80&w=300&h=200",
    confidenceScore: 55,
    statusColor: "warning",
    statusText: "Ambiguous Context",
    logicExplanation: "Deteksi Ambiguitas (Sarkasme):\n\n1. Analisis Teks: Secara leksikal positif ('bagus banget', 'mantap'). Namun terdapat konteks negatif tersembunyi ('hancur berkeping-keping').\n2. Analisis Gambar: Terdeteksi objek rusak/pecah.\n\nKesimpulan: Ambigu (55% Confidence). Teks cenderung sarkasme. Sistem menghentikan otomatisasi penghapusan dan menyarankan [Manual Override] oleh manusia.",
    mobileExplanation: "Halo Ibu, kami mendeteksi kata-kata pembeli ini terdengar memuji, tetapi barangnya tampak hancur di foto. Kami curiga ini komplain/sindiran (sarkas). Mohon Ibu cek sendiri ya apakah ini perlu dihapus atau dibiarkan.",
    isDeleted: false,
    isOverridden: false,
  },
  {
    id: 4,
    productName: "Bluetooth Earbuds (Data Rusak)",
    reviewId: "REV-99211",
    text: "Suaranya kurang ngebass, tapi lumayan buat harga segini.",
    isBlackScreen: false,
    isBrokenData: true,
    imageUrl: "broken-link.jpg",
    confidenceScore: 0,
    statusColor: "warning",
    statusText: "Needs Manual Check",
    logicExplanation: "Data visual tidak terbaca sempurna (Broken Link). Mohon periksa kembali di platform asli. AI tidak dapat melakukan analisis multimodal.",
    mobileExplanation: "Maaf Ibu Ratna, sistem kami tidak bisa mendeteksi foto dari ulasan ini karena adanya gangguan teknis/gambar rusak. Mohon dicek manual.",
    isDeleted: false,
    isOverridden: false,
  }
];
